version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

  celery:
    build: .
    command: celery -A product_crawler worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
