# Generated by Django 4.1.13 on 2024-06-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazondatascrapcollection',
            options={},
        ),
    ]
