# Generated by Django 4.1.13 on 2024-07-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazondatascrapcollection',
            name='request_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_amazon_crawler.scraprequest'),
        ),
    ]
