# Generated by Django 4.1.13 on 2024-07-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0002_amazondatascrapcollection_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazondatascrapcollection',
            old_name='request_id',
            new_name='request',
        ),
    ]
