# Generated by Django 3.1.12 on 2025-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0003_rename_request_id_amazondatascrapcollection_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazondatascrapcollection',
            name='request',
        ),
        migrations.AddField(
            model_name='amazondatascrapcollection',
            name='request_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_amazon_crawler.scraprequest'),
        ),
    ]
