# Generated by Django 3.1.12 on 2025-05-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0004_auto_20250503_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazondatascrapcollection',
            old_name='request_id',
            new_name='request',
        ),
    ]
