# Generated by Django 3.1.12 on 2025-05-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0005_auto_20250503_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='request_reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
