# Generated by Django 3.1.12 on 2025-05-03 13:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_amazon_crawler', '0006_scraprequest_request_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonDataScrapCountry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('navbar_xpath', models.CharField(default='', max_length=255)),
                ('link_xpath', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Amazon Data Scrap Country',
                'verbose_name_plural': 'Amazon Data Scrap Countries',
            },
        ),
        migrations.AlterModelOptions(
            name='amazondatascrapcollection',
            options={'verbose_name': 'Amazon Data Scrap Collection', 'verbose_name_plural': 'Amazon Data Scrap Collections'},
        ),
        migrations.AlterModelOptions(
            name='scraprequest',
            options={'verbose_name': 'Scrap Request', 'verbose_name_plural': 'Scrap Requests'},
        ),
        migrations.AlterField(
            model_name='scraprequest',
            name='request_reason',
            field=models.CharField(default='Request reason not provided.', max_length=255),
        ),
    ]
